INSERT INTO rota (ponto_inicial, ponto_final)VALUES 
('Campo Grande - MS', 'Bonito - MS'),
('Bonito - MS', 'Campo Grande - MS' ),
('Campo Grande - MS', 'São Paulo - SP'),
('São Paulo - SP', 'Campo Grande - MS'),
('Campo Grande - MS', 'Florianópolis - SC'),
('Florianópolis - SC', 'Campo Grande - MS'),
('Campo Grande - MS', 'Rio Branco - AC'),
('Rio Branco - AC', 'Campo Grande - MS'),
('Campo Grande - MS', 'Maceió - AL'),
('Maceió - AL', 'Campo Grande - MS'),
('Campo Grande - MS', 'Macapá - AP'),
('Macapá - AP', 'Campo Grande - MS'),
('Campo Grande - MS', 'Manaus - AM'),
('Manaus - AM', 'Campo Grande - MS'),
('Campo Grande - MS', 'Salvador - BA'),
('Salvador - BA', 'Campo Grande - MS'),
('Campo Grande - MS', 'Fortaleza - CE'),
('Fortaleza - CE', 'Campo Grande - MS'),
('Campo Grande - MS', 'Brasília - DF'),
('Brasília - DF', 'Campo Grande - MS'),
('Campo Grande - MS', 'Vitória - ES'),
('Vitória - ES', 'Campo Grande - MS'),
('Campo Grande - MS', 'Goiânia - GO'),
('Goiânia - GO', 'Campo Grande - MS'),
('Campo Grande - MS', 'São Luís - MA'),
('São Luís - MA', 'Campo Grande - MS'),
('Campo Grande - MS', 'Cuiabá - MT'),
('Cuiabá - MT', 'Campo Grande - MS'),
('Campo Grande - MS', 'Belo Horizonte - MG'),
('Belo Horizonte - MG', 'Campo Grande - MS'),
('Campo Grande - MS', 'Belém - PA'),
('Belém - PA', 'Campo Grande - MS'),
('Campo Grande - MS', 'João Pessoa - PB'),
('João Pessoa - PB', 'Campo Grande - MS'),
('Campo Grande - MS', 'Curitiba - PR'),
('Curitiba - PR', 'Campo Grande - MS'),
('Campo Grande - MS', 'Recife - PE'),
('Recife - PE', 'Campo Grande - MS'),
('Campo Grande - MS', 'Teresina - PI'),
('Teresina - PI', 'Campo Grande - MS'),
('Campo Grande - MS', 'Rio de Janeiro - RJ'),
('Rio de Janeiro - RJ', 'Campo Grande - MS'),
('Campo Grande - MS', 'Natal - RN'),
('Natal - RN', 'Campo Grande - MS'),
('Campo Grande - MS', 'Porto Alegre - RS'),
('Porto Alegre - RS', 'Campo Grande - MS'),
('Campo Grande - MS', 'Porto Velho - RO'),
('Porto Velho - RO', 'Campo Grande - MS'),
('Campo Grande - MS', 'Boa Vista - RR'),
('Boa Vista - RR', 'Campo Grande - MS'),
('Campo Grande - MS', 'Aracaju - SE'),
('Aracaju - SE', 'Campo Grande - MS'),
('Campo Grande - MS', 'Palmas - TO'),
('Palmas - TO', 'Campo Grande - MS')
GO
